### PR TITLE
Bugfix/removing extra database

### LINKED ISSUE #63: (bugfix) removing the extra database
Right now there are two databases used for user accounts. The first database contains username, passwords, etc... (accounts.json) There is now a second database called profile_pic.json that needs to be combined with account.json. There should not be an extra database for new key, that key being "pic_URl". Also the key should not be half uppercase half lowercase. It should either be all uppercase or all lowercase and follow the snake case convention.

### PR DESCRIPTION
**Pull request by gfdb**
removed profile_pic database. Backend for all profile picture functionality has been modified and now uses the already existing accounts database. Also changed some minor label text for signup and login page

### CODE REVIEW

**Review by Omarelk09 — APPROVED** [review]
great job!

**Review by mohamad-elchanati — APPROVED** [review]
Good Job franco. Lets keep it up :)

**Review by david-roper — APPROVED** [review]
Very good change.

**Review by Cresfault — APPROVED** [review]
The code is looking a lot simpler now. Nice job!

**Pull request merged**
