### PR TITLE
Feat/as a user i want to comment backend

### LINKED ISSUE #26: (Feature) As a user, I want to be able to comment on a picture
### **FRONTEND**
The front-end design and functionality for commenting on pictures requires the following:
- Textbox to write comment
- button to post comment
- button to cancel posting a comment
- appropriate design of the comment box 

Story: https://github.com/gianfrancodumoulinbertucci/SOEN341/issues/25

### PR DESCRIPTION
**Pull request by david-roper**
Cancel button now clears comment text box, need more changes to work on all posts.

### CODE REVIEW

**Review by Omarelk09 — APPROVED** [review]
Great job David!

**Review by gfdb — CHANGES_REQUESTED** [review]
I am going to add the backend for #27 on this branch, I think it makes sense.

**Review by Cresfault — APPROVED** [review]
It looks good. There's a little bit of overlap between the front-end and back-end here, so maybe we can check if there is a better way to separate the work.

**Review by gfdb — APPROVED** [review]
Backend changes added, frontend changes looks good.

**Comment by gfdb** [comment]
All changes approved.

**Pull request merged**
