### PR TITLE
adding app.py

### LINKED ISSUE #4: adding app folder
create an app folder for the project

### PR DESCRIPTION
**Pull request by Omarelk09**

### CODE REVIEW

**Review by Cresfault — DISMISSED** [review]
Well done.

**Review by gfdb — APPROVED** [review]
perfect

**Review by Cresfault — APPROVED** [review]
Good job.

**Review by mohamad-elchanati — APPROVED** [review]
Approved

**Review by david-roper — APPROVED** [review]
Very good work!

**Pull request merged**
